### ISSUE TITLE
Feature 

### ISSUE THREAD

**Issue by rubandurai27** [PANDITHAN/Evil-Inside#3]
VC player support & YouTube search or Downloader

**Comment by rubandurai27** [comment]
& Telegraph upload + Force Sub

**Comment by MR-JINN-OF-TG** [comment]
> & Telegraph upload + Force Sub

Ya Sure will add better wait for some days.

**Comment by MR-JINN-OF-TG** [comment]
> VC player support & YouTube search or Downloader
Setter deploy vc bot as another
